name: "Ruby on Rails CI"
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      # Add or replace dependency steps here
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: 3.0.0
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile #rubocop-rspec:gemfile
          reporter: github-pr-check # Default is github-pr-check
      - name: Set up yarn and node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      - name: sqlite3 install
        run: |
          sudo apt install libsqlite3-dev
          gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'
          dpkg -L libsqlite3-dev
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install font
        run: apt install fonts-ipafont fonts-ipaexfont
      # Add or replace test runners here
      - name: run Rspec
        run: bundle exec rspec
      - name: Archive rspec result screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: rspec result screenshots
          path: tmp/screenshots/
